### PR TITLE
Release docs v2.3.0 using maplibre-gl from npm

### PR DESCRIPTION
**Pull request by birkskyum**
We can't update the maplibre-gl-js submodules, but this is an alternative way to update the docs. Installing maplibre-gl as an npm package (>=2.2.0),  while still having the submodule (2.1.9). Build the documentation.js api.json from the newer npm package, and point towards it's package.json files too - but do rely on submodule for the three places we for questionable reasons call into code from maplibre-gl - which are these places:

- import { toString } from ‘../../maplibre-gl-js/rollup/build/tsc/src/style-spec/expression/types’;
- import CompoundExpression from ‘../../maplibre-gl-js/rollup/build/tsc/src/style-spec/expression/compound_expression’;
// registers compound expressions
- import ‘../../maplibre-gl-js/rollup/build/tsc/src/style-spec/expression/definitions/index’;

And also the v8.json from style-spec which is imported 4 places
- import ref from ‘../../maplibre-gl-js/rollup/build/tsc/src/style-spec/reference/latest’;

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by birkskyum** [comment]
@wipfli , @HarelM - I believe this actually worked as expected. 

Versions shows as expected, which is just pulled from the package.json
Screenshot 2022-08-22 at 10 50 51

A new property on the touchpitchhandler is now exposed, which seem to be the only api change:

Screenshot 2022-08-22 at 10 53 38

Screenshot 2022-08-22 at 10 53 19

**Comment by birkskyum** [comment]
I'm currently testing the newest 2.3.0, to see how viable this approach is for us.

**Comment by birkskyum** [comment]
So, we got it. And all the [work](https://github.com/documentationjs/documentation/commits/master ) on documentation.js v14 is now in production :)

**Comment by wipfli** [comment]
Amazing, thanks a lot @birkskyum for updating the docs to the current version!

**Comment by wipfli** [comment]
Can the submodule now be removed?

**Comment by birkskyum** [comment]
No, it cannot. The places we use the submodule as I mentioned in the description of this PR are still in use.

**Comment by birkskyum** [comment]
I'm adding the 3d Terrain example from here: https://maplibre.org/news/2022-05-20-terrain3d/#10.55/47.2751/11.3882/0/52

When I in the docs search for "Terrain#something" it doesn't navigate - how do we fix that?

**Pull request merged**
