### PR TITLE
Bump GL JS to v2.1.1

### PR DESCRIPTION
**Pull request by wipfli**

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Is there a way to automate this?

**Comment by wipfli** [comment]
Let's try. For this, it is good if the project is not updated yet, like it is right now. So please don't merge this pull request for now.

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js-docs/blob/main/.github/workflows/update-gl-js.yml will update to node 16

**Comment by wipfli** [comment]
#118

**Pull request closed without merging**
