### PR TITLE
Bump style spec to v15

### PR DESCRIPTION
**Pull request by wipfli**

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by wipfli** [comment]
#109

**Comment by wipfli** [comment]
Works locally. The style spec is not taken from NPM anymore, because the `.ts` files published there are incompatible with the `.js` source code of the docs website. With this pull request, the transpiled style spec files from the rollup output folder in the GL JS submodule are used. Would be great if you could review, @HarelM

**Comment by HarelM** [comment]
Are we not publishing the style-spec as a different package now? Or was this process using some inner files that were in js and now are no longer accessible due to the ts migration?
Otherwise, looks got to me.

**Comment by wipfli** [comment]
The style spec is published as a separate package: https://www.npmjs.com/package/@maplibre/maplibre-gl-style-spec

Not only the dist files are published, but also all the source files. The source files are now published in TypeScript:

https://unpkg.com/browse/@maplibre/maplibre-gl-style-spec@15.0.0/

and before they were published in JavaScript:

https://unpkg.com/browse/@maplibre/maplibre-gl-style-spec@14.0.0/

The docs website used the JavaScript files, but they are now written in TypeScript so we can not use them anymore. Instead, we can use the transpiled rollup output.

**Comment by HarelM** [comment]
I see. The only problem I see is that the two repos are tightly coupled.
But this was also the case before...

**Review by HarelM — APPROVED** [review]

**Comment by wipfli** [comment]
That's true, the two repos (GL JS and the docs) are tightly coupled. Also, I wonder who actually uses the style spec package separately? Anyway, I will merge once the test passes. Locally it looks good.

**Pull request merged**
