### PR TITLE
Remove mapbox specific code and branding

### PR DESCRIPTION
**Pull request by marcelnormann**
Happy reverse engineering of uglyfied code

### CODE REVIEW

**Comment by marcelnormann** [comment]
Last unsolved problem: /maplibre-gl-js-docs/assets/favicon/site.webmanifest?v=rMBbQAR5BL not found in debug server, but found when statically served.

**Comment by marcelnormann** [comment]
Still some minor but hard to fix bugs left, but none of this is additionally to ones in the main branch. I think this is ready for production.

**Comment by wipfli** [comment]
Thanks for working on this. Please remove the hard-coded version reference and use a dynamic one.

**Review by wipfli — COMMENTED** [review]
Does the order matter in `layout: example`?

**Comment by marcelnormann** [comment]
> Does the order matter in `layout: example`?

No, it does not. I ran a script to ensure all files have a hideFeedback attribute. This also resorted the order of attributes unintentionally. I will fix this within an additional commit. After squashing the PR this noise should be removed.

**Review by wipfli — APPROVED** [review]
Thanks for the clean-up Marcel.

**Pull request merged**
