### PR TITLE
Example for 3D model on map using babylon.js

### PR DESCRIPTION
**Pull request by kaliatech**
I based this example on the existing three.js example.

Also:
 - Minor correction to newer NPM command in README.
 - The image create tool seemed to not work so I created thumbnail manually.

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by kaliatech** [comment]
Of course, let me know if you don't want another 3D example. I can also post this example over on the Babylon.js forums/docs instead.

**Comment by HarelM** [comment]
Can you please fix build failures?

**Comment by HarelM** [comment]
The more the merrier 😀

**Comment by kaliatech** [comment]
I added a fix commit the build-test error, but then build failed again. Looking at log, I think it failed this time due to network error with NPM and failure is unrelated to any code changes. I assume you have some way to retrigger the build. Otherwise, I can add a dummy commit.

**Review by HarelM — APPROVED** [review]

**Pull request merged**
