### PR TITLE
Update Mapillary tile layer endpoint

### PR DESCRIPTION
**Pull request by cbeddow**
Changed endpoint, and changed layer name

### CODE REVIEW

**Comment by astridx** [comment]
I checked http://localhost:8080/maplibre-gl-js-docs/example/third-party/ after calling `npm start` in this repo. 

1mapillary

Then I applied this branch (https://github.com/maplibre/maplibre-gl-js-docs/pull/57/files).  

2mapillary

Both times Mapillar Tiles are OK.

According to the documentation (https://www.mapillary.com/developer/tiles-documentation/), the changes are also fine.

@cbeddow,  Will the old specifications for tiles (https://d25uarhxywzl1j.cloudfront.net/v0.1/{z}/{x}/{y}.mvt) and source-layer (mapillary-sequences) become invalid?

**Comment by cbeddow** [comment]
@astridx yes the old endpoint will expire in the next few weeks or months and the specifications are no longer valid for the new endpoints

**Review by wipfli — APPROVED** [review]
Looks good to me

**Comment by wipfli** [comment]
Thanks @cbeddow for updating the example and thans @astridx for reviewing 😄

**Pull request merged**
