### PR TITLE
Readme - GNU build essential are needed in the case of Ubuntu/Debian

### PR DESCRIPTION
**Pull request by astridx**
I had to install this and would give it to others as a hint.

### CODE REVIEW

**Review by lseelenbinder — APPROVED** [review]
Looks good to me.

@wipfli do you know if sure this requirement is due to different Node versions where some requirement binary isn't already built for that Node + OS version?

**Comment by wipfli** [comment]
Thanks for this. I would like to check in a docker ubuntu container if the build essentials are really needed. Did you run `nvm`? I am a bit worried that this error is tied to your specific computer.

**Comment by astridx** [comment]
@wipfli Yes I run `nvm.`
I installed the repo it on a newly installed machine and `npm install` asked for the `make`  command. After installing the tools everything run well.

**Comment by wipfli** [comment]
Hi Astrid. So when running ubuntu in docker container I am not able to reproduce your error. Everything works fine for me.

What I run was:

```bash
docker run -it --rm ubuntu
apt update
apt install git nodejs npm -y
git clone https://github.com/maplibre/maplibre-gl-js-docs.git
git clone https://github.com/maplibre/maplibre-gl-js.git
mkdir maplibre-gl-js/dist
cd maplibre-gl-js-docs/
npm ci
git submodule update --init
npm start
```

Can you maybe make a docker example which reproduces the error you had?

**Comment by astridx** [comment]
@wipfli 
OK. Thank you for checking and sorry for bothering. Maybe it depends on my machine.

**Pull request closed without merging**
