### PR TITLE
Use demotiles for simple-map.html example

### PR DESCRIPTION
**Pull request by wipfli**
image

### CODE REVIEW

**Comment by wipfli** [comment]
@klokan something like that?

**Review by nyurik — APPROVED** [review]
lgtm!

**Comment by astridx** [comment]
Is there a reason why this change was made for one example and not for all?

**Comment by wipfli** [comment]
Many examples use map data at deeper zoom levels. The demotiles so far not well suited for them because the demotiles basically only show country borders.

**Comment by astridx** [comment]
OK. Thank you for the answer.

**Comment by wipfli** [comment]
Everyone from the steering committee, including Petr Pridal (@klokan) from maptiler, agrees that the docs website should be as vendor-independent as possible. If you are interested in working on more complete demotiles for example around cities that are used in the examples we would all welcome that.

**Pull request merged**
