### PR TITLE
Migrate to new Style docs

### PR DESCRIPTION
**Pull request by birkskyum**
Continuation of 
https://github.com/maplibre/maplibre-style/pull/88

Closes
https://github.com/maplibre/maplibre-gl-js/issues/2149
https://github.com/maplibre/maplibre-gl-js-docs/issues/417

This removes the "Style specification" tab on the left, but there is still the link on the front page to the new docs:

Screenshot 2023-04-06 at 20 38 00

### CODE REVIEW

**Review by HarelM — APPROVED** [review]
Can we add a redirect rule somewhere from old urls to new ones? I would like to avoid breaking all the existing urls that are not part of the docs if possible.

**Comment by birkskyum** [comment]
That would be cloudflare - I can have a look at it.

**Comment by birkskyum** [comment]
Here are examples of the old urls that should redirect when it's configured correct

https://maplibre.org/maplibre-gl-js-docs/style-spec/
https://maplibre.org/maplibre-gl-js-docs/style-spec/sprite/
https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#ramps-scales-curves

**Comment by HarelM** [comment]
So how should I get to the spec documentation? I couldn't find it in the latest version...

**Comment by birkskyum** [comment]
From the front page

**Comment by HarelM** [comment]
I see, yea, that was my next question. Please open an issue on it as it's hard to find this link now and I would like to see that we can solve this later on.

**Comment by birkskyum** [comment]
#455

**Pull request merged**
