### PR TITLE
Update package-lock.json and pin node version

### PR DESCRIPTION
**Pull request by wipfli**
Should fix the broken CI...

### CODE REVIEW

**Comment by HarelM** [comment]
Can you share what part breaks?
In maplibre-gl there's a problem with nide 16.14 and above so we use 16.13, I think...

**Comment by wipfli** [comment]
Npm ci fails on main. I think the default node version changed. For this pull request, I used nvm use 16.15
1 on my laptop to fix the lock file.

**Comment by HarelM** [comment]
I don't mind approving, but it still looks broken. Am I missing anything?

**Comment by wipfli** [comment]
Now it says it can't find a package: 

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mapbox/remark-lint-mapbox/-/remark-lint-mapbox-2.4.0.tgz - Not found
```

**Comment by wipfli** [comment]
https://www.npmjs.com/search?q=%40mapbox%2Fremark-lint-mapbox returns no package, strange...

**Comment by wipfli** [comment]
Maybe this package as removed?

```
npm install --save @mapbox/remark-lint-mapbox                             
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mapbox%2fremark-lint-mapbox - Not found
npm ERR! 404 
npm ERR! 404  '@mapbox/remark-lint-mapbox@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wipfli/.npm/_logs/2022-07-07T04_55_06_356Z-debug-0.log
```

**Comment by wipfli** [comment]
I think it builds for me locally because I have the missing package in my cache.

**Comment by wipfli** [comment]
In github code spaces, I get `npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mapbox/remark-lint-mapbox/-/remark-lint-mapbox-2.4.0.tgz - Not found` as well. I suggest we remove this package...

**Comment by HarelM** [comment]
Sounds right...

**Comment by wipfli** [comment]
I will merge this to main and then merge it to #211

**Pull request merged**
