### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by wipfli**
This pull request changes to logo in the top left corner of the page from mapbox to maplibre:

logo

Demo can be found at https://wipfli.github.io/maplibre-gl-js-docs/

I have used the svg file from https://github.com/maplibre/maplibre-gl-js/issues/82 and added some random colors. 

In ```vendors/docs-page-shell/page-shell-styles.css``` there is also a white variant of the logo which needs to be updated from mapbox to maplibre.

### CODE REVIEW

**Comment by nyurik** [comment]
I thought we were doing a much less flashy blue/light blue text/color?  The multicolors of this one is just too much imo

**Comment by wipfli** [comment]
Yes, absolutely the multi color is just for fun. It serves more as a placeholder for where the real logo should go.

Is there already a consensus for the color theme of maplibre? I like blue but should it be exactly the same as mapbox, i.e. ```#4264fb```?

**Comment by nyurik** [comment]
I don't think we should copy mapbox's color here :)  Rather, I think we should simply use the dark blue + light blue combination, as agreed during the last sync - https://github.com/maplibre/maplibre-gl-js/issues/65#issuecomment-782772391

Going forward, we can always revisit the design of the logo :)

**Comment by wipfli** [comment]
Thanks for pointing me to this comment @nyurik. 

I close this pull request. Please have a look at https://github.com/maplibre/maplibre-gl-js-docs/pull/6.

**Pull request closed without merging**
