### PR TITLE
Update submodule

### PR DESCRIPTION
**Pull request by birkskyum**
Dependabot managed to trick me, so I revert the package-updates that broke the CI and start by updating the submodule so that it's version doesn't break the CI.

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by wipfli** [comment]
Thanks for the updates, @birkskyum. Does this build locally for you?

**Comment by wipfli** [comment]
Maybe you have to update this line:

https://github.com/maplibre/maplibre-gl-js-docs/blob/98222c22a9ed28ab8e170c3dfb5e78e70c468b9a/package.json#L68

**Comment by birkskyum** [comment]
it seems like documentation.js is behaving as expected, but this batfish static site generator is not happy about the ' import assert json' yet, even with the barbell plugin injected

**Comment by wipfli** [comment]
If I build on main without the added plugin from this pull request against https://github.com/maplibre/maplibre-gl-js/pull/1517 I get this error:
```
> documentation build --pe ts --re ts --re d.ts --github --format json --sort-order alpha --config ./docs/documentation.yml --output docs/components/api.json maplibre-gl-js/src/index.ts

SyntaxError: This experimental syntax requires enabling the parser plugin: 'importAssertions' (2:42)
```

**Comment by wipfli** [comment]
But removing the asserts and using the plugin seems to work...

**Comment by birkskyum** [comment]
When the current pre-release of maplibre-gl-js is out, I was planning on having another look at this. It turns out the documentation.js runs just fine, import asserts and all. It's the mapbox/batfish static site generator that doesn't know how to handle it yet.

**Comment by wipfli** [comment]
I think that's right, yes.

**Comment by wipfli** [comment]
Maybe we have to put the assert plugin here? https://github.com/mapbox/batfish/blob/78938bb7638c33111806982672d93792d52ee3ce/package.json#L67

**Comment by birkskyum** [comment]
I did try that here https://github.com/birkskyum/batfish/commit/93bc42143f1b7da194045d1713d14363bc280f54 - something is still off, but it does load the plugin.

It's equivalent to adding this next to `babelInclude` in batfish.config.json.
```ts
		babelPlugins: [
          "@babel/plugin-syntax-import-assertions"
        ],
```

**Comment by birkskyum** [comment]
This PR has come too far out of sync, so I'll make a new one when the repo is ready for a submodule change.

**Pull request closed without merging**
